PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/40ff30ed7116afa9ab8e2d15299ce4802c0d3ccd

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/904a602c74dc08a100b5c2bd490807de19e73e10) in current PX4/master (5e855c67477fe08517297a38e718ed1102536cf6)
https://github.com/PX4/NuttX/compare/904a602c74dc08a100b5c2bd490807de19e73e10...40ff30ed7116afa9ab8e2d15299ce4802c0d3ccd

40ff30ed71 (HEAD, origin/master) boards/arm/stm32f0l0g0/b-l072z-lrwan1/src/stm32_ssd1306.c: Fix a syslog format
a70961ec9d arch/arm/src/stm32f0l0g0/stm32_adc.c: Fix syslog formats
597675bd7f drivers/mmcsd/mmcsd_sdio.c: Fix a syslog format
fc76157d4a arch/arm/src/stm32f0l0g0/stm32_spi.c: Fix syslog formats
5706e3851d drivers/wireless/lpwan/sx127x/sx127x.c: Fix syslog formats
b299fdf1e3 arch/arm/src/stm32f7/stm32_ethernet.c: Fix syslog formats
0dee21503d fs/spiffs/src/spiffs_mtd.c: Fix syslog formats
be013cc338 fs/spiffs/src/spiffs_gc.c: Fix syslog formats
a6b4c1b755 fs/spiffs/src/spiffs_core.c: Fix syslog formats
88bc46f4a6 fs/spiffs/src/spiffs_vfs.c: Fix syslog formats

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/72d9b34fb13958b5798a180f815257446f57f597

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/909eff540d8004371d5838b9c0764cc753d665cf) in current PX4/master (5e855c67477fe08517297a38e718ed1102536cf6)
https://github.com/PX4/NuttX-apps/compare/909eff540d8004371d5838b9c0764cc753d665cf...72d9b34fb13958b5798a180f815257446f57f597

72d9b34f (HEAD -> master, origin/master) netutils/tftpc/tftpc_put.c: Fix syslog formats
5a4bf6b3 netutils/tftpc/tftpc_get.c: Fix a syslog format
eeded9da netutils/ntpclient/ntpclient.c: Fix syslog formats
13424fc4 netutils/ftpc/ftpc_putfile.c: Fix syslog formats
2a3f2ea8 netutils/ftpc/ftpc_putfile.c: Appease nxstyle
7b3ccfa9 netutils/ftpc/ftpc_getfile.c: Fix a syslog format
f83caca9 netutils/ftpc/ftpc_getfile.c: Appease nxstyle
24b6f919 examples/mld: Fix undefined reference to `mld_catfile'
a4ae1592 examples/i2schar: Fix the compile error
736a21f0 examples/chrono: Rename button_daemon to chrono_daemon